=== Melero1/LLMSGI/Tema3DTD/Ejercicio2DTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT minecraftItems (item+)>
<!ATTLIST minecraftItems lang CDATA #REQUIRED>

<!ELEMENT item (name, type, material?, rarity, (damage | defensa)?, enchantment?, durabilidad, description)>
<!ATTLIST item
    id CDATA #REQUIRED
    crafteable (true | false) #REQUIRED
    enchantments (true | false) #REQUIRED 
>

<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT material (#PCDATA)>
<!ELEMENT rarity (#PCDATA)>
<!ELEMENT damage (#PCDATA)>
<!ELEMENT defensa (#PCDATA)>
<!ELEMENT enchantment (#PCDATA)>
<!ELEMENT durabilidad (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== Melero1/LLMSGI/Tema3DTD/Ejercicio2XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE minecraftItems SYSTEM "Ejercicio2DTD.dtd">
<minecraftItems lang="es">
   <item id="1" crafteable="true" enchantments="true">
        <name>Espada de diamante</name>
        <type>Arma</type>
        <material>diamante</material>
        <rarity>Epico</rarity>
        <damage>7</damage>
        <enchantment>Golpe V, Filo V</enchantment>
        <durabilidad>20000</durabilidad>
        <description>Espada de diamante</description>
   </item>
   <item id="2" crafteable="true" enchantments="true">
        <name>Casco de diamante</name>
        <type>Armadura</type>
        <material>diamante</material>
        <rarity>Epico</rarity>
        <defensa>5</defensa>
        <enchantment>Defensa V</enchantment>
        <durabilidad>17000</durabilidad>
        <description>Armadura de diamante</description>
    </item>
    <item id="3" crafteable="true" enchantments="true">
        <name>Peto de diamante</name>
        <type>Armadura</type>
        <material>diamante</material>
        <rarity>Epico</rarity>
        <defensa>8</defensa>
        <enchantment>Defensa V</enchantment>
        <durabilidad>19000</durabilidad>
        <description>Armadura de diamante</description>
    </item>
    <item id="4" crafteable="true" enchantments="true"> 
        <name>Pantalones de diamante</name>
        <type>Armadura</type>
        <material>diamante</material>
        <rarity>Epico</rarity>
        <defensa>7</defensa>
        <enchantment>Defensa V</enchantment>
        <durabilidad>18000</durabilidad>
        <description>Armadura de diamante</description>
    </item>
    <item id="5" crafteable="true" enchantments="true">
        <name>Botas de diamante</name>
        <type>Armadura</type>
        <material>diamante</material>
        <rarity>Epico</rarity>
        <defensa>5</defensa>
        <enchantment>Defensa V</enchantment>
        <durabilidad>17000</durabilidad>
        <description>Armadura de diamante</description>
    </item>
</minecraftItems>
