=== Melero1/LLMSGI/Tema3DTD/Ejercicio7DTD.dtd
<!ELEMENT Ejercicio7XML (factura+)>
<!ATTLIST Ejercicio7XML lang CDATA #REQUIRED>

<!ELEMENT factura (fecha, menbrete, cliente, productos, resumen)>
<!ATTLIST factura facturaNumero CDATA #REQUIRED>

<!ELEMENT fecha (#PCDATA)>

<!ELEMENT menbrete (razonSocial, direccion, codigoPostal, poblacion, telefono, email)>
<!ATTLIST menbrete cif CDATA #REQUIRED>
<!ELEMENT razonSocial (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT codigoPostal (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT cliente (nombre, direccion, codigoPostalCliente, poblacionCliente)>
<!ATTLIST cliente dni CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT codigoPostalCliente (#PCDATA)>
<!ELEMENT poblacionCliente (#PCDATA)>

<!ELEMENT productos (producto+)>
<!ELEMENT producto (cantidad, descripcion, precioUnitario, iva)>
<!ATTLIST producto codigo CDATA #REQUIRED>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT precioUnitario (#PCDATA)>
<!ELEMENT iva (#PCDATA)>

<!ELEMENT resumen (formaPago, descuento)>
<!ELEMENT formaPago (#PCDATA)>
<!ELEMENT descuento (#PCDATA)>

=== Melero1/LLMSGI/Tema3DTD/Ejercicio7XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Ejercicio7XML SYSTEM "Ejercicio7DTD.dtd">

<Ejercicio7XML lang="es">
    
    <factura facturaNumero="1">   
        
       <fecha>04/11/2024</fecha> 

        <menbrete cif="123456789">
            <razonSocial>Todos Unidos</razonSocial>
            <direccion>Calle de la esperanza</direccion>
            <codigoPostal>03730</codigoPostal>
            <poblacion>Madrid</poblacion>
            <telefono>755847595</telefono>
            <email>TodosUnidos@gmail.com</email>
        </menbrete>

        <cliente dni="987654321A">
            <nombre>Juan Pedro</nombre>
            <direccion>Calle pedrito Navaja</direccion>
            <codigoPostalCliente>02450</codigoPostalCliente>
            <poblacionCliente>Barcelona</poblacionCliente>
        </cliente>

        <productos>
            <producto codigo="001">
                <cantidad>3</cantidad>
                <descripcion>Limpieza</descripcion>
                <precioUnitario>4.00</precioUnitario>
                <iva>0.20</iva>
            </producto>
            <producto codigo="002">
                <cantidad>1</cantidad>
                <descripcion>Carne</descripcion>
                <precioUnitario>8.00</precioUnitario>
                <iva>0.80</iva>
            </producto>
            <producto codigo="003">
                <cantidad>8</cantidad>
                <descripcion>Limpieza</descripcion>
                <precioUnitario>0.80</precioUnitario>
                <iva>0.05</iva>
            </producto>

        </productos>
        
        <resumen>
            <formaPago>transferencia</formaPago>
            <descuento>0.00</descuento>
        </resumen>
    </factura>
</Ejercicio7XML>
